### ISSUE TITLE
List of IDs to each file

### ISSUE THREAD

**Issue by BeyondTheHorizon** [shadowfox87/YGOAnimeMangaHQPics#1]
Is there a file that stores data of which images correspond to each ID? I thought the "index" file would, but when I open it it just says the ID and then gobbledygook.

For example, I know that "100000116.jpg" is "Arcana Force XV - The Fiend", but I can't find a file that tells me explicitly which IDs link to each image. With the TCGOCG images, one can simply look up their ID, but here there's really no way of knowing. If there isn't a file, would it be possible to create one?

**Comment by shadowfox87** [comment]
The cards.cdb contains the link of which id belongs to which card. For anime cards, it's cards-anime.cdb. You can find my other repository here: https://github.com/shadowfox87/animescripts
to get the latest cdb.

**Comment by BeyondTheHorizon** [comment]
Ah, okay. Thank you for the information. This thread may be marked as closed.
